version: "3.9"

services:
  web:
    build: .
    command: python games_database/manage.py runserver 0.0.0.0:8000 --verbosity 3
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    labels:
      net.unraid.docker.managed: 'composeman'
      net.unraid.docker.icon: 'https://whatemoji.org/wp-content/uploads/2020/07/Game-Die-Emoji.png'
      net.unraid.docker.webui: 'unraid.home:8000'
